apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: postgres-replica
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    # Replace with your actual git repo URL
    repoURL: https://github.com/Hemanth88970/postgres.git
    targetRevision: main
    path: replica
  destination:
    server: https://kubernetes.default.svc
    namespace: postgres-ha
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
